ExUnit.start()

[
  "SALESFORCE_ENDPOINT",
  "SALESFORCE_CLIENT_ID",
  "SALESFORCE_CLIENT_SECRET",
  "SALESFORCE_USERNAME",
  "SALESFORCE_PASSWORD",
  "SALESFORCE_SECURITY_TOKEN",
  "SALESFORCE_API_VERSION"
]
|> Enum.map(&System.delete_env/1)
